## UFSM00041 - MATEMÁTICA COMPUTACIONAL II
### Atividade Avaliativa #2
#### Prof. Tiago Buriol   - 1º Semestre de 2024

#### **Nome do aluno**: Vitor Dallabona 

**1.** Use o algoritmo de eliminação de Gauss para resolver os seguintes sistemas lineares, se possível, e determine se são necessárias trocas de linhas

$$
\begin{aligned}
x_1+x_2+x_4 & =2, \\
2 x_1+x_2-x_3+x_4 & =1, \\
4 x_1-x_2-2 x_3+2 x_4 & =0, \\
3 x_1-x_2-x_3+2 x_4 & =-3 .
\end{aligned}
\quad \quad \quad
\begin{aligned}
2 x_1 & =3 \\
x_1+1,5 x_2 & =4,5 \\
-3 x_2+0,5 x_3 & =-6,6 \\
2 x_1-2 x_2+x_3+x_4 & =0,8
\end{aligned}
$$

In [61]:
import numpy as np

# funções para o método de Gauss
def escalonap(M):
    n = len(M)
    for j in range(n-1):

        m = M[j:,j:]
        idx=np.flip(np.argsort(abs(m[:,0])))
        M[j:,j:] = m[idx]

        for i in range(j,n-1):
            m = M[i+1,j]/M[j,j]
            M[i+1] = M[i+1]-m*M[j]

    return (M)

def escalona2(M):
    n = len(M)
    for j in range(n-1):
        for i in range(j,n-1): 
            # rolando as linhas
            while M[j,j]==0:
                M[j:,:] = np.roll(M[j:,:], -1, axis=0)
                
            m = M[i+1,j]/M[j,j]
            M[i+1] = M[i+1]-m*M[j]
    return (M)


def escalona(M):
    n = len(M)
    for j in range(n-1):
        for i in range(j,n-1):
            m = M[i+1,j]/M[j,j]
            M[i+1] = M[i+1]-m*M[j]
    return (M)


def solve_U(U,b):
    n=len(b)
    x = np.empty(n)
    for i in range(n-1, -1, -1):
        x[i] = (b[i] - np.sum(U[i,i+1:n+1]*x[i+1:n+1]))/U[i,i]
    return x

def solve_tril(L,b):
    y = np.empty(len(b))
    for i in range(len(b)): 
        y[i] = (b[i] - np.dot(L[i,0:i],y[0:i]))/L[i][i] 
    return y

In [57]:
# resolvendo o primeiro sistema
A = np.array([[1, 1, 0, 1],
             [2, 1, -1, 1],
             [4, -1, -2, 2],
             [3, -1, -1, 2]], dtype = float)

b = np.array([2, 1, 0 , -3], dtype = float)

Ampliada = np.hstack((A,b.reshape(4,1)))
print(Ampliada)
Ampliada_esc = escalona(Ampliada)  
Aesc1 =  Ampliada_esc[:,:-1]
besc1 = Ampliada_esc[:,-1]

S1 = solve_U(Aesc1, besc1)

print (S1)

[[ 1.  1.  0.  1.  2.]
 [ 2.  1. -1.  1.  1.]
 [ 4. -1. -2.  2.  0.]
 [ 3. -1. -1.  2. -3.]]
[ nan  nan  inf -inf]


C:\Users\vitor\AppData\Local\Temp\ipykernel_21632\2079091415.py:44: RuntimeWarning: divide by zero encountered in scalar divide
  x[i] = (b[i] - np.sum(U[i,i+1:n+1]*x[i+1:n+1]))/U[i,i]
C:\Users\vitor\AppData\Local\Temp\ipykernel_21632\2079091415.py:44: RuntimeWarning: invalid value encountered in multiply
  x[i] = (b[i] - np.sum(U[i,i+1:n+1]*x[i+1:n+1]))/U[i,i]


In [45]:
#o erro acima pode ser devido à uma divisão que foi feita por 0, logo é necessário escalonar a matriz com pivôs para ver se o resultado é alterado

In [58]:
Ampliada_esc_piv = escalonap(Ampliada)
print (Ampliada_esc_piv)
Aesc2 =  Ampliada_esc_piv[:,:-1] # separando as matrizes para implementar a função solve
besc2 = Ampliada_esc_piv[:,-1]

S2 = solve_U(Aesc2, besc2)

print (S2)

[[ 1.  1.  0.  1.  2.]
 [ 0. -1. -1. -1. -3.]
 [ 0.  0.  3.  3.  7.]
 [ 0.  0.  0.  0. -4.]]
[ nan  nan  inf -inf]


C:\Users\vitor\AppData\Local\Temp\ipykernel_21632\2079091415.py:44: RuntimeWarning: divide by zero encountered in scalar divide
  x[i] = (b[i] - np.sum(U[i,i+1:n+1]*x[i+1:n+1]))/U[i,i]
C:\Users\vitor\AppData\Local\Temp\ipykernel_21632\2079091415.py:44: RuntimeWarning: invalid value encountered in multiply
  x[i] = (b[i] - np.sum(U[i,i+1:n+1]*x[i+1:n+1]))/U[i,i]


In [47]:
# Novamente o erro está presente, e portanto o sistema da esquerda não possui soluções. 
# Outra forma de observar que o sistema não posssui solução é notar que o posto da matriz 
# ampliada escalonada não coincide com o posto da matriz dos coeficientes.

In [59]:
# resolvendo o segundo sistema

A = np.array([[2, 0, 0, 0],
             [1, 1.5, 0, 0],
             [0, -3, 0.5, 0],
             [2, -2, 1, 1]], dtype = float)

b = np.array([3, 4.5, -6.6 , 0.8], dtype = float)

Ampliada = np.hstack((A,b.reshape(4,1)))
print(Ampliada)
Ampliada_esc = escalona(Ampliada)
Aesc1 =  Ampliada_esc[:,:-1]
besc1 = Ampliada_esc[:,-1]

S1 = solve_U(Aesc1, besc1)

print("Solução:")
print (S1)

[[ 2.   0.   0.   0.   3. ]
 [ 1.   1.5  0.   0.   4.5]
 [ 0.  -3.   0.5  0.  -6.6]
 [ 2.  -2.   1.   1.   0.8]]
Solução:
[ 1.5  2.  -1.2  3. ]


**2.** Use o algoritmo de eliminação de Gauss-Jordan obter a inversa da matriz dos coeficientes dos sistema lineares da questão 1. Então, obtenha a solução usando a matriz inversa.

In [39]:
# função para o método de Gauss-Jordan
def gaussJordan(M):
    n = len(M)
    for k in range(n):
        M[k] = M[k]/M[k,k]
        for i in range(n):
            if i!=k:
                M[i] = M[i] - M[i,k]*M[k]
    return (M)

In [62]:
# notemos que o primeiro sistema não possui inversa:

A = np.array([[1, 1, 0, 1],
             [2, 1, -1, 1],
             [4, -1, -2, 2],
             [3, -1, -1, 2]], dtype = float)

I = np.identity(len(A)) # matriz identidade da ordem de A
M = np.concatenate((A,I), axis=1)
print ('Matriz ampliada:')
print (M)

Matriz ampliada:
[[ 1.  1.  0.  1.  1.  0.  0.  0.]
 [ 2.  1. -1.  1.  0.  1.  0.  0.]
 [ 4. -1. -2.  2.  0.  0.  1.  0.]
 [ 3. -1. -1.  2.  0.  0.  0.  1.]]


In [63]:
print ('Matriz após eliminação:')
Mgj = gaussJordan(M)
print (np.round(Mgj,2))

Matriz após eliminação:
[[ nan  nan  nan  nan  inf -inf  inf -inf]
 [ nan  nan  nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  inf -inf  inf -inf]
 [ nan  nan  nan  nan -inf  inf -inf  inf]]


C:\Users\vitor\AppData\Local\Temp\ipykernel_21632\4290762504.py:5: RuntimeWarning: divide by zero encountered in divide
  M[k] = M[k]/M[k,k]
C:\Users\vitor\AppData\Local\Temp\ipykernel_21632\4290762504.py:5: RuntimeWarning: invalid value encountered in divide
  M[k] = M[k]/M[k,k]
C:\Users\vitor\AppData\Local\Temp\ipykernel_21632\4290762504.py:8: RuntimeWarning: invalid value encountered in multiply
  M[i] = M[i] - M[i,k]*M[k]


In [40]:
# Como o primeiro sistema não possui solução, calculemos a inversa do segundo sistema

A = np.array([[2, 0, 0, 0],
             [1, 1.5, 0, 0],
             [0, -3, 0.5, 0],
             [2, -2, 1, 1]], dtype = float)

b = np.array([3, 4.5, -6.6 , 0.8], dtype = float)

I = np.identity(len(A)) # matriz identidade da ordem de A
M = np.concatenate((A,I), axis=1)
print ('Matriz ampliada:')
print (M)

Matriz ampliada:
[[ 2.   0.   0.   0.   1.   0.   0.   0. ]
 [ 1.   1.5  0.   0.   0.   1.   0.   0. ]
 [ 0.  -3.   0.5  0.   0.   0.   1.   0. ]
 [ 2.  -2.   1.   1.   0.   0.   0.   1. ]]


In [48]:
print ('Matriz após eliminação:')
Mgj = gaussJordan(M)
print (np.round(Mgj,2))

Matriz após eliminação:
[[ 1.    0.    0.    0.    0.5   0.    0.    0.  ]
 [ 0.    1.    0.    0.   -0.33  0.67  0.    0.  ]
 [ 0.    0.    1.    0.   -2.    4.    2.    0.  ]
 [ 0.    0.    0.    1.    0.33 -2.67 -2.    1.  ]]


In [49]:
from numpy.linalg import inv
Ainv = Mgj[:,4:8]
print("Matrz inversa:")
print(Ainv) # matriz inversa

# solução
print("Solução:")
x = np.dot(inv(A),b)
print(x)

Matrz inversa:
[[ 0.5         0.          0.          0.        ]
 [-0.33333333  0.66666667  0.          0.        ]
 [-2.          4.          2.          0.        ]
 [ 0.33333333 -2.66666667 -2.          1.        ]]
Solução:
[ 1.5  2.  -1.2  3. ]


**3.** Dados os dois sistemas lineares $4 \times 4$ tendo a mesma matriz de coeficientes:

$$
\begin{aligned}
x_1-x_2+2 x_3-x_4 & =6, \\
x_1-x_3+x_4 & =4, \\
2 x_1+x_2+3 x_3-4 x_4 & =-2, \\
-x_2+x_3-x_4 & =5 ;
\end{aligned}
\quad \quad \quad \quad 
\begin{aligned}
x_1-x_2+2 x_3-x_4 & =1 \\
x_1-x_3+x_4 & =1 \\
2 x_1+x_2+3 x_3-4 x_4 & =2 \\
-x_2+x_3-x_4 & =-1 .
\end{aligned}
$$

Resolva os sistemas lineares aplicando eliminação de Gauss-Jordan à matriz aumentada 

$$
\left[\begin{array}{rrrrlrr}
1 & -1 & 2 & -1 & \vdots & 6 & 1 \\
1 & 0 & -1 & 1 & \vdots & 4 & 1 \\
2 & 1 & 3 & -4 & \vdots & -2 & 2 \\
0 & -1 & 1 & -1 & \vdots & 5 & -1
\end{array}\right]
\text{.}
$$


In [54]:
A = np.array([[1, -1, 2, -1],
             [1, 0, -1, 1],
             [2, 1, 3, -4],
             [0, -1, 3, -1]], dtype = float)

b1 = np.array([6, 4, -2, 5],dtype = float)

b2 = np.array([1, 1, 2 , -1], dtype = float)

I = np.identity(len(A)) # matriz identidade da ordem de A
M = np.concatenate((A,I), axis=1)
print ('Matriz ampliada:')
print (M)

Matriz ampliada:
[[ 1. -1.  2. -1.  1.  0.  0.  0.]
 [ 1.  0. -1.  1.  0.  1.  0.  0.]
 [ 2.  1.  3. -4.  0.  0.  1.  0.]
 [ 0. -1.  3. -1.  0.  0.  0.  1.]]


In [55]:
print ('Matriz após eliminação:')
Mgj = gaussJordan(M)
print (np.round(Mgj,2))

Matriz após eliminação:
[[ 1.    0.    0.    0.    0.12  0.62  0.12  0.  ]
 [ 0.    1.    0.    0.   -1.62  0.88  0.38  1.  ]
 [ 0.    0.    1.    0.   -0.88  0.62  0.12  1.  ]
 [ 0.    0.    0.    1.   -1.    1.    0.    1.  ]]


In [55]:
x1 = np.dot(inv(A),b1)
print(x1)

x2 = np.dot(inv(A),b2)
print(x2)

[ 3. -2.  2.  3.]
[ 1. -1. -1. -1.]


**4.** Resolva o sistema linear utilizando fatoração $LU$ (imprima as matrizes $L$ e $ U$). Faça trocas de linhas se necessário.

$$
\begin{aligned}
2 x_1+x_2 & =0, \\
-x_1+3 x_2+3 x_3 & =5, \\
2 x_1-2 x_2+x_3+4 x_4 & =-2, \\
-2 x_1+2 x_2+2 x_3+5 x_4 & =6 .
\end{aligned}
$$

In [56]:
def fatoraLU(A):
    L = np.eye(len(A))
    U = A.copy()
    n = len(A)
    for j in range(n-1):
        for i in range(j,n-1):
            m = U[i+1,j]/U[j,j]
            U[i+1] = U[i+1]-m*U[j]
            L[i+1,j] = m
    return (L,U)


def solve_tril(L,b):
    y = np.empty(len(b))
    for i in range(len(b)):
        y[i] = (b[i] - np.dot(L[i,0:i],y[0:i]))/L[i][i]
    return y


def solve_triu(U,y):
    n=len(y)
    x = np.empty(n)
    for i in range(n-1, -1, -1):
        x[i] = (y[i] - np.sum(U[i,i+1:n+1]*x[i+1:n+1]))/U[i,i]

In [57]:
A = np.array([[2, 1, 0, 0],
             [-1, 3, 3, 0],
             [2, -2, 1, 4],
             [-2, 2, 2, 5]], dtype = float)

b = np.array([0, 5, -2, 6],dtype = float)

L,U = fatoraLU(A)
print(L)
print(U)

[[ 1.          0.          0.          0.        ]
 [-0.5         1.          0.          0.        ]
 [ 1.         -0.85714286  1.          0.        ]
 [-1.          0.85714286 -0.16        1.        ]]
[[2.         1.         0.         0.        ]
 [0.         3.5        3.         0.        ]
 [0.         0.         3.57142857 4.        ]
 [0.         0.         0.         5.64      ]]


In [58]:
 # de fato, se multiplicarmos as duas, vemos que é a matriz original
np.dot(L,U)

array([[ 2.,  1.,  0.,  0.],
       [-1.,  3.,  3.,  0.],
       [ 2., -2.,  1.,  4.],
       [-2.,  2.,  2.,  5.]])

In [59]:
y = solve_tril(L,b) #resolvendo Ly = b
print(y)

x = solve_triu(U,y) #resolvendo Ux = y para obter a solução
print(x)

[0.         5.         2.28571429 2.08      ]
None


**5.** Faça trocas de linhas se necessário e use algum método iterativo para resolver o sistema linear 
$$
\begin{aligned}
-x_1-x_2+5 x_3+x_4 & =0, \\
x_1+4 x_2-x_3-x_4 & =-1, \\
4 x_1+x_2-x_3+x_4 & =-2, \\
x_1-x_2+x_3+3 x_4 & =1 
\end{aligned}
$$

com tolerância $10^{-5}$ para alguma norma. Quantas iterações foram necessárias?

In [60]:
A = np.array([[-1, -1, 5, 1],
             [1, 4, -1, -1],
             [4, 1, -1, 1],
             [1, -1, 1, 3]], dtype = float)

b = np.array([0, -1, -2, 1],dtype = float)

A[[0,2]] = A[[2,0]]
print(A)

[[ 4.  1. -1.  1.]
 [ 1.  4. -1. -1.]
 [-1. -1.  5.  1.]
 [ 1. -1.  1.  3.]]


In [61]:
H = A.copy()
g = b.copy()

for i in range(len(A)):
    H[i] = -A[i]/A[i,i]
    g[i] = b[i]/A[i,i]

H = H + np.identity(len(A))

norma_inf = np.sum(abs(A), axis=1).max()
print ('Norma:', norma_inf)

Norma: 8.0


In [62]:
# função para fazer as iterações

def itera(x):
    x1 = (b[0] - A[0,1]*x[1] - A[0,2]*x[2])/A[0,0]
    x2 = (b[1] - A[1,0]*x[0] - A[1,2]*x[2])/A[1,1]
    x3 = (b[2] - A[2,0]*x[0] - A[2,1]*x[1])/A[2,2]
    x = np.array([x1, x2, x3])
    return x

# fazendo as iterações
err = 1
x = np.array([0,0,0])
x_ant = x
i = 0

print ('Iterações:')
while err > 0.00001:
    x = itera(x)
    err = np.max(abs(x-x_ant))/np.max(abs(x))
    x_ant = x
    i += 1
    print (i, x, np.round(err,4))

print ("Solução:", np.round(x,4))

Iterações:
1 [ 0.   -0.25 -0.4 ] 1.0
2 [-0.0375 -0.35   -0.45  ] 0.2222
3 [-0.025    -0.353125 -0.4775  ] 0.0576
4 [-0.03109375 -0.363125   -0.475625  ] 0.021
5 [-0.028125   -0.36113281 -0.47884375] 0.0067
6 [-0.02942773 -0.36267969 -0.47785156] 0.0032
7 [-0.02879297 -0.36210596 -0.47842148] 0.0013
8 [-0.02907888 -0.36240713 -0.47817979] 0.0006
9 [-0.02894316 -0.36227523 -0.4782972 ] 0.0003
10 [-0.02900549 -0.36233851 -0.47824368] 0.0001
11 [-0.02897629 -0.36230955 -0.4782688 ] 0.0001
12 [-0.02898981 -0.36232313 -0.47825717] 0.0
13 [-0.02898351 -0.36231684 -0.47826259] 0.0
14 [-0.02898644 -0.36231977 -0.47826007] 0.0
Solução: [-0.029  -0.3623 -0.4783]


In [63]:
# foram necessárias 14 iterações